2021-04-07 13:56:35,309 ERROR: Exception on /socketo1 [GET] [in /home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sora8d/Documents/Code/FAIF/application/socketo/so.py", line 8, in WORK
    return render_template('socketo/SIO.html')
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: socketo/SIO.html
2021-04-07 13:56:59,366 ERROR: Exception on /socketo1 [GET] [in /home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sora8d/Documents/Code/FAIF/application/socketo/so.py", line 8, in WORK
    return render_template('socketo/SIO.html')
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/sora8d/Documents/Code/FAIF/application/templates/socketo/SIO.html", line 4, in template
    <link rel="stylesheet" href="{{ url_for('static' filename='SIO.css') }}">
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'filename'
2021-04-07 13:59:36,548 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 14:08:53,094 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 14:12:06,983 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 14:35:26,397 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 14:38:29,004 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 14:40:12,166 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 14:47:18,590 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 14:48:51,504 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 14:49:28,986 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 14:51:43,729 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 14:53:23,204 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 14:54:16,394 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 14:54:58,561 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 14:58:24,457 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 14:59:42,165 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 15:00:27,590 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 15:03:55,168 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 15:07:40,224 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 15:34:10,577 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 21:26:18,679 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 21:29:18,612 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 21:29:40,078 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 21:30:30,648 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 21:31:53,244 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 21:39:27,207 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 21:40:22,217 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 21:40:45,527 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 21:41:10,672 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 21:41:34,446 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 21:41:50,337 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 21:44:15,537 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 21:46:04,550 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 21:47:44,731 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 21:48:36,706 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 21:48:43,736 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 21:50:03,910 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 21:53:45,389 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 21:56:14,028 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 21:57:36,477 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 21:58:47,343 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
2021-04-07 21:59:53,964 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:84]
